version: "3.8" 
services:
  api:
    container_name: mapmaker
    build:
      context: .
      dockerfile: Dockerfile
    expose: 
      - "8080"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/usr/src/app
    tty: true
    env_file:
      - .env
